package com.jobportal.dto.ai;

import lombok.*;
import java.util.List;

/**
 * Structured output from AI-powered resume parsing.
 * This represents the semantic understanding of a resume.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ResumeProfile {

    /**
     * Skills extracted with relevance weights.
     */
    private List<WeightedSkill> skills;

    /**
     * Key experiences summarized.
     */
    private List<String> experiences;

    /**
     * Important keywords extracted from the resume.
     */
    private List<String> keywords;

    /**
     * Brief professional summary generated by AI.
     */
    private String summary;

    /**
     * Inferred experience level: FRESHER, JUNIOR, MID, SENIOR, LEAD
     */
    private String experienceLevel;

    /**
     * Total years of experience estimated.
     */
    private Double totalYearsExperience;

    /**
     * Preferred job roles inferred from resume.
     */
    private List<String> preferredRoles;
}
